---
title: "ANOVA_models"
author: "David Chen"
date: "4/27/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}
# Clear environment
rm(list = ls())

# Load packages
library(readxl)
library(tidyverse)   
library(broom)      # For tidy() to make better anova summary
library(knitr)      # For better tables

# Read in data
AS_raw <- read_excel("Data/AlkaSeltzer_Results.xlsx")
```

---

# Data cleaning

```{r}
AS <-
  AS_raw %>%
  mutate(Volume = as.factor(Volume))
```

---


# ANOVA model

```{r}
# Start with the full model with 2 and 3 way interactions
full_aov <- 
  aov(Time ~ Temp + Liquid + Volume + Temp:Liquid + Temp:Volume + Liquid:Volume + Temp:Liquid:Volume, 
                data = AS)

# Conduct the stepwise selection
step_aov <- step(full_aov, trace = FALSE)
```


```{r}
# Better anova summary table
step_aov %>%
  tidy() %>%
  kable(digits = 3)
```


```{r}
# Predictions using the optimal fator levels
preds <- data.frame(Temp = "Room", Liquid = "Water")
predict(step_aov, newdata = preds)
```



# Residual Plots
```{r}
par(mfrow = c(1,3))
plot(step_aov)

```



---

## Tukey Comparisons

```{r}
TukeyHSD(step_aov, "Temp", conf.level = 0.95) 

TukeyHSD(step_aov, "Liquid", conf.level = 0.95)
```

```{r}
TukeyHSD(step_aov, "Temp", conf.level = 0.95) %>%
  tidy() %>%
  select(-null.value) %>%
  kable(digits = 2) 

TukeyHSD(step_aov, "Liquid", conf.level = 0.95) %>%
  tidy() %>%
  select(-null.value) %>%
  kable(digits = 2)
```





Tukey plots

```{r}
plot(TukeyHSD(step_aov, "Temp", conf.level = 0.95)) 

plot(TukeyHSD(step_aov, "Liquid", conf.level = 0.95))
```




